version: '3.9'
services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME:-wisebird_docker}_php
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./../../app:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    user: www-data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME:-wisebird_docker}_nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - ${NGINX_PORT:-80}:80
    depends_on:
      - php
    volumes:
      - ./../../app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME:-wisebird_docker}_postgres
    image: postgres:14
    environment:
      - POSTGRES_USER=${DB_USER:-dbuser}
      - POSTGRES_PASSWORD=${DB_PASS:-dbpass}
      - POSTGRES_DB=${DB_NAME:-dbname}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - data-postgres:/var/lib/postgresql/data
      - ./../../app/var/log/postgres/:/var/log/postgresql/

volumes:
  data-postgres:
    name: ${COMPOSE_PROJECT_NAME:-wisebird_docker}_data_postgres
