framework:
    secret: '%env(APP_SECRET)%'

    session: false

    serializer:
        enabled: true

    csrf_protection: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

